[versions]
androidGradlePlugin = "9.4.0"
androidxActivity = "1.13.0"
androidxAppcompat = "1.8.0"
androidxConstraintlayout = "2.2.2"
material = "1.14.0"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidxActivity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintlayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }