[versions]
androidxAppcompat = "1.8.0"
androidxExifinterface = "1.4.2"
androidxActivity = "1.13.0"
googleMaterial = "1.14.0"
androidGradlePlugin = "9.4.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidxExifinterface" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidxActivity" }
google-material = { module = "com.google.android.material:material", version.ref = "googleMaterial" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
